# -*- coding: utf-8 -*-
"""Copy of Copy of Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/TSFDlib/TSFDlib/blob/master/TSFDlib.ipynb
"""

#@title Import Time Series Features Library
!git clone https://github.com/TSFDlib/TSFDlib.git >/dev/null 2>&1
!pip install --upgrade -q gspread >/dev/null 2>&1
!pip install gspread oauth2client >/dev/null 2>&1
!pip install pandas >/dev/null 2>&1
!pip install scipy >/dev/null 2>&1
!pip install novainstrumentation >/dev/null 2>&1
!pip install pandas_profiling >/dev/null 2>&1

#@title Extract Features
import pandas as pd
import pandas_profiling
import numpy as np
import TSFDlib as tslib

window_size = 5
t = np.array(pd.read_csv('TSFDlib/data/input_signal/Signal.txt'))[:,0]
signal = np.array(pd.read_csv('TSFDlib/data/input_signal/Signal.txt'))[:,1]
cfg_file = tslib.extract_sheet()
  
df = tslib.extract_features(signal, window_size, cfg_file)

#@title Features
df

#@title Correlation Report

from IPython.display import display, HTML, IFrame
display(HTML('CorrelationReport.html'))